# -*- coding: utf-8 -*-
"""
PAPER_BERT_Decoding_Transformers_Spectra_full_graphs.py
========================================================
Automatically generated by Colab.
Original file: https://colab.research.google.com/drive/1YgyVLdndyGZ0xwOxOHZq8_d7SF2k3ZhA

Decoding Transformers Spectra: A Random Matrix Theory Framework
Beyond the Marchenko-Pastur Law
------------------------------------------------------------------------

This script implements the full analysis pipeline for the paper, applied to
BERT-base-uncased (12 layers, hidden_size=768, intermediate_size=3072).

BERT-base vs. BERT-Large differences
--------------------------------------
* 12 encoder layers (vs. 24 in Large).
* hidden_size = 768 (vs. 1024).
* Key weight shapes:
    - attention Q/K/V/output : (768, 768)   β = 1.0  (square)
    - FFN intermediate       : (3072, 768)  β = 0.25 (rectangular)
    - FFN output             : (768, 3072)  β = 0.25 (rectangular)
* Layer split for scenario functions: layers 0-5 vs. 6-11 (halfway at 6).
* Graph 11 includes a duplicated 768×768 shape entry for the pooler/output
  dense layer, handled by a deduplication suffix in the results dict.

Structural note
---------------
Unlike the BERT-Large script, Graphs 1-3 in this file share a single set
of helper functions and a single SETTINGS list defined in the Graph 1 block.
Graphs 4 and 5 re-define helpers locally for self-containment; Graphs 6-12
are also self-contained.

Pipeline overview
-----------------
1. ``extract_matrices``  — Download BERT-base and save all qualifying 2-D
                           weight matrices as .npy files with a manifest.
2. Build W_MP (Sec. 2)   — Column-standardise: W_MP = (W − μ) / σ.
3. Graphs 1-12           — Mosaic diagnostic figures.

Random Matrix Theory background
--------------------------------
For an m×n random matrix with i.i.d. zero-mean unit-variance entries,
the empirical spectral distribution of W^T W / max(m,n) converges to:

    ρ_MP(λ; β) = sqrt[(b−λ)(λ−a)] / (2π β λ),    λ ∈ [a, b]

where  a = (1 − √β)²,  b = (1 + √β)²,  β = min(m,n)/max(m,n).
"""

# =============================================================================
# SECTION 1 — EXTRACT WEIGHT MATRICES FROM BERT-BASE-UNCASED
# =============================================================================

# extract_bert_matrices.py
from pathlib import Path
import json
import numpy as np
import torch
from transformers import BertModel


def extract_matrices(
    model_name: str = "bert-base-uncased",
    out_dir: str = "bert_weights",
    include_bias: bool = False,
    only_linear_like: bool = True,      # skip LayerNorm/embeddings unless 2-D
    dtype: str = "float32",             # "float32" | "float64"
    save_format: str = "npy",           # "npy" | "npz" (np.savez_compressed)
):
    """
    Download BERT-base from HuggingFace and save all qualifying 2-D weight matrices.

    Iterates the full ``state_dict`` for robustness (covers all submodules),
    converts qualifying tensors to NumPy arrays, and writes them to a mirrored
    directory tree inside ``out_dir``.  A JSON manifest records the original
    parameter name, relative file path, shape, and dtype for every saved array.
    Embedding matrices are additionally saved under ``out_dir/embeddings/``.

    Key path mapping
    ----------------
    ``"encoder.layer.N.attention.self.query.weight"``
    → ``out_dir/encoder/layer_N/attention/self/query/weight.npy``

    The token ``"layer"`` is dropped and the following integer N is prefixed
    with ``"layer_"`` to produce valid directory names.

    Parameters
    ----------
    model_name : str
        HuggingFace model identifier, default ``"bert-base-uncased"``.
    out_dir : str
        Root directory for saved weights and the manifest.
    include_bias : bool
        If ``True``, 1-D bias vectors (matched by ``"bias"`` substring) are
        also saved (default: ``False``).
    only_linear_like : bool
        If ``True`` (default), keep only 2-D tensors whose parameter name
        contains one of the recognised linear-layer fragments:
        ``"encoder.layer"``, ``"attention"``, ``"intermediate"``,
        ``"output.dense"``, ``"self.query"``, ``"self.key"``,
        ``"self.value"``, ``"dense"``, ``"pooler.dense"``.
    dtype : str
        NumPy dtype for saved arrays: ``"float32"`` (default) or ``"float64"``.
    save_format : str
        ``"npy"`` (default) or ``"npz"`` (compressed, key ``"data"``).

    Side effects
    ------------
    Creates ``out_dir`` and sub-directories as needed.
    Writes one array file per qualifying parameter plus
    ``out_dir/manifest.json``.

    Prints
    ------
    Resolved output path and total number of saved tensors.
    """
    assert save_format in {"npy", "npz"}
    np_dtype = np.float32 if dtype == "float32" else np.float64  # noqa: F841

    # Load model in inference mode on CPU to avoid unnecessary GPU allocation
    torch.set_grad_enabled(False)
    model = BertModel.from_pretrained(model_name)
    model.eval()
    model.to("cpu")

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    # Iterate state_dict for robustness — covers all submodules uniformly
    sd = model.state_dict()
    manifest = {
        "model_name": model_name,
        "dtype": dtype,
        "include_bias": include_bias,
        "only_linear_like": only_linear_like,
        "files": []
    }

    def keep_param(key: str, tensor: torch.Tensor) -> bool:
        """
        Return True if this parameter should be saved.

        Accepts 2-D tensors matching recognised linear/attention/FFN name
        fragments when ``only_linear_like`` is True.  Optionally includes
        1-D bias vectors when ``include_bias`` is True.
        """
        # Want weights (2-D) from linear/attention/FFN; optionally biases (1-D)
        if tensor.ndim == 2:
            if only_linear_like:
                # Heuristics: keep common linear/attention/FFN matrices
                names_we_like = (
                    "encoder.layer", "attention", "intermediate", "output.dense",
                    "self.query", "self.key", "self.value", "dense", "pooler.dense"
                )
                return any(n in key for n in names_we_like)
            return True

        if include_bias and tensor.ndim == 1:
            names_we_like = ("bias",)
            return any(n in key for n in names_we_like)

        return False

    # ---- Save qualifying tensors ----
    for key in sorted(sd.keys()):
        t = sd[key]
        if not keep_param(key, t):
            continue

        arr = t.detach().cpu().to(
            dtype=torch.float32 if dtype == "float32" else torch.float64
        ).numpy()

        # Build a safe, hierarchical path from the dotted parameter key.
        # Example: "encoder.layer.0.attention.self.query.weight"
        #       -> encoder/layer_0/attention/self/query/weight.npy
        parts = key.split(".")
        # Normalize "layer.N" to "layer_N"
        norm_parts = []
        for p in parts:
            if p == "layer":
                continue              # "layer" is implicit in the directory name
            if p.isdigit():           # the index that follows "layer"
                norm_parts.append(f"layer_{p}")
            else:
                norm_parts.append(p)

        # All but the last part form the directory; last part is the filename stem
        save_dir = out.joinpath(*norm_parts[:-1])
        save_dir.mkdir(parents=True, exist_ok=True)

        stem = norm_parts[-1]   # "weight" or "bias"
        ext  = ".npy" if save_format == "npy" else ".npz"
        path = save_dir / f"{stem}{ext}"

        if save_format == "npy":
            np.save(path, arr)
        else:
            np.savez_compressed(path, data=arr)

        manifest["files"].append({
            "name":  key,
            "path":  str(path.relative_to(out)),
            "shape": list(arr.shape),
            "ndim":  arr.ndim,
            "dtype": str(arr.dtype)
        })

    # ---- Save embedding matrices separately (optional grouping) ----
    # Comment out this block if a separate embeddings folder is not needed.
    emb_dir = out / "embeddings"
    emb_dir.mkdir(exist_ok=True)
    for subkey, param in model.embeddings.state_dict().items():
        if param.ndim == 2 or (include_bias and param.ndim == 1):
            arr = param.detach().cpu().to(
                dtype=torch.float32 if dtype == "float32" else torch.float64
            ).numpy()
            fname = (
                subkey.replace(".", "_")
                + ("_bias" if subkey.endswith("bias") else "")
                + (".npy" if save_format == "npy" else ".npz")
            )
            path = emb_dir / fname
            if save_format == "npy":
                np.save(path, arr)
            else:
                np.savez_compressed(path, data=arr)

            manifest["files"].append({
                "name":  f"embeddings.{subkey}",
                "path":  str(path.relative_to(out)),
                "shape": list(arr.shape),
                "ndim":  arr.ndim,
                "dtype": str(arr.dtype)
            })

    # ---- Write manifest ----
    with open(out / "manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"Saved to: {out.resolve()}")
    print(f"Total tensors saved: {len(manifest['files'])}")


if __name__ == "__main__":
    extract_matrices(
        model_name="bert-base-uncased",
        out_dir="bert_weights",
        include_bias=False,
        only_linear_like=True,
        dtype="float32",
        save_format="npy",
    )


# =============================================================================
# SECTION 2 — BUILD W_MP (COLUMN-STANDARDISED MATRICES) AND SAVE STATS
# =============================================================================
"""
Build W_MP and save column-wise statistics for downstream inversion.

Inputs
------
bert_weights/        Directory produced by Section 1.

Outputs
-------
step1_column_stats.json
    Human-readable summary: per-matrix mean-of-means, mean-of-stds,
    max/min std, and NPZ key names for exact recovery.
step1_column_stats.npz
    Compressed archive storing exact per-column μ and σ arrays.
bert_weights_WMP/
    Mirror of bert_weights/ containing W_MP arrays plus manifest.json.

Transformation
--------------
W_MP = (W − 1·μᵀ) / σ    (column-wise, broadcast over rows)

Zero-variance columns are left unchanged (divided by 1.0 to avoid NaN).
"""

import json
import re
from datetime import datetime, UTC
from pathlib import Path
import numpy as np

# ---- Path constants ----
WEIGHTS_DIR = "bert_weights"
STATS_JSON  = "step1_column_stats.json"
STATS_NPZ   = "step1_column_stats.npz"
WMP_DIR     = "bert_weights_WMP"


def _safe_key(idx: int, kind: str, name: str) -> str:
    """
    Build a stable, filesystem-safe NPZ key for per-column statistics.

    The key has the form ``{idx:04d}__{kind}__{sanitised_name}`` where
    ``kind`` is ``"mean"`` or ``"std"``.  Non-alphanumeric characters in
    ``name`` are replaced with underscores, consecutive underscores are
    collapsed, and the result is capped at 200 characters.

    Parameters
    ----------
    idx : int
        Zero-based index of the matrix in the manifest.
    kind : str
        ``"mean"`` or ``"std"``.
    name : str
        Original HuggingFace parameter name.

    Returns
    -------
    str
        A ≤200-character NPZ-safe key string.
    """
    base = f"{idx:04d}__{kind}__" + re.sub(r"[^0-9a-zA-Z_]+", "_", name)
    base = re.sub(r"__+", "__", base).strip("_")
    return base[:200]


def _load_matrix(path: Path) -> np.ndarray:
    """
    Load a NumPy array from a ``.npy`` or ``.npz`` file.

    For ``.npz`` files the array is expected under the key ``"data"``.

    Parameters
    ----------
    path : Path
        Path to the file.

    Returns
    -------
    np.ndarray
        The stored array.

    Raises
    ------
    ValueError
        If the file extension is neither ``.npy`` nor ``.npz``.
    """
    if path.suffix == ".npy":
        return np.load(path)
    if path.suffix == ".npz":
        return np.load(path)["data"]
    raise ValueError(f"Unsupported file type: {path.suffix}")


def _save_npy(path: Path, arr: np.ndarray) -> None:
    """
    Save a NumPy array to ``path``, creating parent directories as needed.

    Parameters
    ----------
    path : Path
        Destination file path (should end in ``.npy``).
    arr : np.ndarray
        Array to save.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    np.save(path, arr)


# ---- Step 2-A: compute and save column-wise statistics ----
weights_dir   = Path(WEIGHTS_DIR)
manifest_path = weights_dir / "manifest.json"
assert manifest_path.exists(), f"Manifest not found at {manifest_path}"

with open(manifest_path, "r") as f:
    manifest = json.load(f)

npz_store = {}
stats_json = {
    "model_name": manifest.get("model_name", ""),
    "created_at": datetime.now(UTC).isoformat(),
    "weights_dir": str(weights_dir),
    "count_files": 0,
    "files": []
}

files     = manifest.get("files", [])
processed = 0

for idx, entry in enumerate(files):
    relpath = entry.get("path")
    name    = entry.get("name", relpath)
    shape   = entry.get("shape")

    fpath = weights_dir / relpath
    if not fpath.exists():
        print(f"[MISS] {relpath}")
        continue

    try:
        W = _load_matrix(fpath)
    except Exception as e:
        print(f"[LOAD-ERR] {relpath}: {e}")
        continue

    if W.ndim != 2:
        continue   # only 2-D matrices are included in the analysis

    # Compute column-wise statistics in float64 for numerical stability
    W  = W.astype(np.float64, copy=False)
    mu = W.mean(axis=0)   # shape (n_cols,)
    sd = W.std(axis=0)    # shape (n_cols,)

    mean_key = _safe_key(idx, "mean", name)
    std_key  = _safe_key(idx, "std",  name)
    npz_store[mean_key] = mu
    npz_store[std_key]  = sd

    stats_json["files"].append({
        "index": idx,
        "name":  name,
        "path":  relpath,
        "shape": shape,
        "npz_keys": {"mean": mean_key, "std": std_key},
        "summary": {
            "mean_of_means": float(mu.mean()),
            "mean_of_stds":  float(sd.mean()),
            "max_std":       float(sd.max()),
            "min_std":       float(sd.min())
        }
    })
    processed += 1
    if processed % 25 == 0:
        print(f"[STATS] Processed {processed} matrices...")

stats_json["count_files"] = processed

with open(STATS_JSON, "w") as jf:
    json.dump(stats_json, jf, indent=2)
np.savez_compressed(STATS_NPZ, **npz_store)

print(f"[STATS] Done. Matrices processed: {processed}")
print(f"[STATS] JSON: {STATS_JSON}")
print(f"[STATS] NPZ : {STATS_NPZ}")

# ---- Step 2-B: build W_MP and save with its own manifest ----
out_root = Path(WMP_DIR)
out_root.mkdir(parents=True, exist_ok=True)

wmp_manifest = {
    "model_name":       manifest.get("model_name", "") + " (column-standardized)",
    "dtype":            "float64",
    "include_bias":     manifest.get("include_bias", False),
    "only_linear_like": manifest.get("only_linear_like", True),
    "files": []
}

stats_npz = np.load(STATS_NPZ)

saved   = 0
skipped = 0

for entry in stats_json["files"]:
    relpath = entry["path"]
    name    = entry["name"]
    mu      = stats_npz[entry["npz_keys"]["mean"]]   # per-column means
    sd      = stats_npz[entry["npz_keys"]["std"]]    # per-column std devs

    src_path = weights_dir / relpath
    if not src_path.exists():
        print(f"[MISS-WMP] {relpath}")
        continue

    W = _load_matrix(src_path)
    if W.ndim != 2:
        skipped += 1
        continue

    W = W.astype(np.float64, copy=False)

    # Guard zero-variance columns: divide by 1.0 leaves them unchanged
    safe_sd = np.where(sd == 0, 1.0, sd)

    # Column-wise standardisation: W_MP = (W − μ) / σ
    WMP = (W - mu.reshape(1, -1)) / safe_sd.reshape(1, -1)

    dst_path = out_root / relpath
    _save_npy(dst_path, WMP)

    wmp_manifest["files"].append({
        "name":  name.replace(".weight", ".weight_WMP"),
        "path":  str(dst_path.relative_to(out_root)),
        "shape": list(WMP.shape),
        "ndim":  2,
        "dtype": str(WMP.dtype)
    })
    saved += 1
    if saved % 25 == 0:
        print(f"[WMP] Saved {saved} matrices...")

with open(out_root / "manifest.json", "w") as f:
    json.dump(wmp_manifest, f, indent=2)

# ---- Step 2-C: round-trip verification on the first 3 matrices ----
from itertools import islice


def _check_one(relpath: str, mu: np.ndarray, sd: np.ndarray) -> float:
    """
    Verify that W can be exactly recovered from W_MP, μ, and σ.

    Computes the maximum absolute reconstruction error:
    ``max |W − (W_MP · σ + μ)|``

    Parameters
    ----------
    relpath : str
        Relative path to the original weight file inside ``WEIGHTS_DIR``.
    mu : np.ndarray, shape (n,)
        Per-column mean vector.
    sd : np.ndarray, shape (n,)
        Per-column standard deviation vector.

    Returns
    -------
    float
        Maximum absolute reconstruction error.
    """
    W       = _load_matrix(weights_dir / relpath).astype(np.float64)
    WMP     = _load_matrix(out_root / relpath).astype(np.float64)
    safe_sd = np.where(sd == 0, 1.0, sd)
    W_rec   = WMP * safe_sd.reshape(1, -1) + mu.reshape(1, -1)
    return float(np.max(np.abs(W - W_rec)))


print("====================================================")
print(f"✅ WMP saved: {saved} | Skipped (non-2D): {skipped}")
print(f"Manifest written: {out_root / 'manifest.json'}")

errs = []
for e in islice(stats_json["files"], 3):
    rel = e["path"]
    mu  = stats_npz[e["npz_keys"]["mean"]]
    sd  = stats_npz[e["npz_keys"]["std"]]
    errs.append((rel, _check_one(rel, mu, sd)))
for rel, err in errs:
    print(f"[CHECK] {rel}: max |W - (WMP*sd+mu)| = {err:.3e}")
print("====================================================")


# =============================================================================
# GRAPHS 1-3 — SHARED HELPERS AND SETTINGS
# =============================================================================
"""
Graphs 1, 2, and 3 are self-contained within a single code block in this
file.  The helpers (_load_matrix, _mp_support, etc.) and the SETTINGS list
are defined once here and reused by all three figures.  The shared design
avoids redundant code at the cost of sequential execution dependency.

BERT-base-uncased matrix shapes
---------------------------------
* attention Q/K/V/output (768×768)  : β_override = 1.00  (square)
* FFN intermediate (3072×768)       : β_override = 0.25  (rectangular)
* FFN output (768×3072)             : β_override = 0.25  (rectangular)

Six parameter sets span layers 0, 5, and 11 to sample early, middle,
and final encoder representations.
"""

import json
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

# ---- Global Matplotlib style (paper-ready, Times New Roman / STIX) ----
plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
    "mathtext.fontset": "stix",
    "font.size": 7,
    "axes.titlesize": 7,
    "axes.labelsize": 7,
    "xtick.labelsize": 5,
    "ytick.labelsize": 5,
    "legend.fontsize": 5,
    "axes.linewidth": 0.6,
    "lines.linewidth": 1.2,
    "grid.linewidth": 0.4,
    "grid.alpha": 0.3,
    "pdf.fonttype": 42,   # embed fonts as Type 1 in PDF output
    "ps.fonttype": 42,
})

# ---- Shared MP helper functions (used by Graphs 1-3) ----

def _load_matrix(p: Path):
    """Load array from .npy (direct) or .npz (key 'data')."""
    if p.suffix == ".npy":  return np.load(p)
    if p.suffix == ".npz":  return np.load(p)["data"]
    raise ValueError(f"Unsupported file type: {p.suffix}")


def _mp_support(beta: float):
    """
    Lower and upper bulk-edge support of the MP distribution.

    Returns a = (1−√β)², b = (1+√β)² for aspect ratio β = min/max.
    """
    r = np.sqrt(beta)
    return (1 - r)**2, (1 + r)**2


def _mp_pdf(x, beta, a, b):
    """
    Marchenko-Pastur PDF: √[(b−λ)(λ−a)] / (2π β λ) on [a,b], else 0.

    Parameters
    ----------
    x : array_like
        Evaluation points (eigenvalues λ).
    beta, a, b : float
        MP shape parameter and support edges.

    Returns
    -------
    np.ndarray
        PDF values; zero outside [a, b].
    """
    x   = np.asarray(x, dtype=np.float64)
    out = np.zeros_like(x)
    m   = (x >= a) & (x <= b)
    xm  = np.clip(x[m], 1e-15, None)   # guard against λ = 0
    out[m] = np.sqrt((b - xm) * (xm - a)) / (2 * np.pi * beta * xm)
    return out


def _cumtrapz_np(y, x):
    """
    Cumulative trapezoidal integration without SciPy.

    Returns a cumulative integral array starting at 0, same length as y.
    """
    dx  = np.diff(x)
    seg = 0.5 * (y[:-1] + y[1:]) * dx
    return np.concatenate([[0.0], np.cumsum(seg)])


def _mp_cdf(x, beta, grid_points=8192):
    """
    Marchenko-Pastur CDF evaluated numerically.

    Uses the substitution g(t) = a + (b−a)·t² to concentrate quadrature
    points near the lower edge where the PDF has an integrable singularity.

    Parameters
    ----------
    x : array_like
        Evaluation points.
    beta : float
        MP shape parameter.
    grid_points : int
        Number of quadrature points (default 8192).

    Returns
    -------
    np.ndarray
        CDF values in [0, 1].
    """
    a, b = _mp_support(beta)
    t    = np.linspace(0.0, 1.0, grid_points)
    g    = a + (b - a) * t * t   # substitution resolves lower-edge singularity
    pdf  = _mp_pdf(g, beta, a, b)
    cdf_vals = _cumtrapz_np(pdf, g)
    cdf_vals /= cdf_vals[-1]     # normalise to exactly 1
    return np.interp(x, g, cdf_vals, left=0.0, right=1.0)


def _edge_margin(beta, m, n, trim_kind, c_tw, frac_sq, frac_rect):
    """
    Compute the edge trimming margin δ for defining the interior MP bulk.

    Three strategies:
    * ``"tw"``             — Tracy-Widom scale: c_tw · n_eff^{-2/3} · (1+√β)^{4/3}
    * ``"fraction"``       — Fixed fraction of bulk bandwidth (b−a).
    * ``"tw_or_fraction"`` — max(TW margin, fractional margin)  [default].

    Parameters
    ----------
    beta : float
        Aspect ratio.
    m, n : int
        Matrix dimensions.
    trim_kind : str
        One of the three strategies above.
    c_tw : float
        TW constant multiplier.
    frac_sq : float
        Fractional trim for square matrices (m == n).
    frac_rect : float
        Fractional trim for rectangular matrices.

    Returns
    -------
    float
        Trimming margin δ ≥ 0.
    """
    a, b      = _mp_support(beta)
    bandwidth = b - a
    n_eff     = min(m, n)
    is_square = (m == n)
    tw   = c_tw * (n_eff ** (-2/3)) * (1 + np.sqrt(beta))**(4/3)
    frac = (frac_sq if is_square else frac_rect) * bandwidth
    if trim_kind == "tw":             return tw
    if trim_kind == "fraction":       return frac
    if trim_kind == "tw_or_fraction": return max(tw, frac)
    raise ValueError("Invalid trim_kind")


def _find_manifest_entry(manifest, target):
    """
    Locate a matrix entry in a W_MP manifest by name or path fragment.

    Tries exact name match first, then substring search on both
    ``"name"`` and ``"path"`` fields.

    Parameters
    ----------
    manifest : dict
        Loaded manifest JSON (must have a ``"files"`` list).
    target : str
        Full or partial matrix name.

    Returns
    -------
    dict
        The matching manifest entry.

    Raises
    ------
    ValueError
        If no entry matches.
    """
    for e in manifest["files"]:
        if e.get("name", "") == target: return e
    for e in manifest["files"]:
        if target in e.get("name", "") or target in e.get("path", ""): return e
    raise ValueError(f"Matrix '{target}' not found in manifest")


def compute_trimmed(W, TRIM_KIND, C_TW, EDGE_FRAC_SQUARE, EDGE_FRAC_RECT, beta_override=None):
    """
    Compute the trimmed interior eigenvalue spectrum and conditional MP functions.

    Steps
    -----
    1. SVD of W; convert to scaled eigenvalues λ_i = s_i² / max(m, n).
    2. Compute trim margin δ.
    3. Keep only λ ∈ [a + δ, b − δ].
    4. Build conditional MP PDF and CDF renormalised to [L, U].

    Parameters
    ----------
    W : np.ndarray, shape (m, n)
        Column-standardised weight matrix (W_MP).
    TRIM_KIND : str
        Edge trimming strategy.
    C_TW : float
        TW constant multiplier.
    EDGE_FRAC_SQUARE : float
        Fractional trim for square matrices.
    EDGE_FRAC_RECT : float
        Fractional trim for rectangular matrices.
    beta_override : float or None
        If provided, use this β instead of min(m,n)/max(m,n).
        BERT-base uses 0.25 (rectangular FFN) or 1.00 (square attention).

    Returns
    -------
    lam_trim : np.ndarray
        Sorted interior eigenvalues surviving the trim.
    (a, b, L, U, beta) : tuple of float
        Full support edges, trim boundaries, and β used.
    mp_pdf_cond : callable
        Conditional MP PDF: ρ_MP(λ) / (F_MP(U) − F_MP(L)).
    mp_cdf_cond : callable
        Conditional MP CDF clipped to [0, 1].
    N_trim : int
        Number of eigenvalues surviving the trim.
    """
    m, n  = W.shape
    beta  = beta_override if beta_override is not None else min(m, n) / max(m, n)
    s     = np.linalg.svd(W, full_matrices=False, compute_uv=False)
    lambdas = (s**2) / max(m, n)
    lambdas.sort()

    a, b  = _mp_support(beta)
    delta = _edge_margin(beta, m, n, TRIM_KIND, C_TW,
                         EDGE_FRAC_SQUARE, EDGE_FRAC_RECT)
    L, U  = a + delta, b - delta

    # Fall back to full support if the margin collapses the interval
    if L >= U:
        L, U = a, b

    mask     = (lambdas >= L) & (lambdas <= U)
    lam_trim = lambdas[mask]
    N_trim   = lam_trim.size

    FL, FU = _mp_cdf([L, U], beta)
    den    = max(FU - FL, 1e-12)

    mp_pdf_cond = lambda x: _mp_pdf(x, beta, a, b) / den
    mp_cdf_cond = lambda x: np.clip((_mp_cdf(x, beta) - FL) / den, 0, 1)

    return lam_trim, (a, b, L, U, beta), mp_pdf_cond, mp_cdf_cond, N_trim


# ---- Shared plot configuration ----
WMP_DIR   = "bert_weights_WMP"
COND_GRID = 2000    # number of x-axis evaluation points for MP curve
HIST_BINS = 150     # histogram bins for the empirical density

# BERT-base-uncased: 12 layers, hidden=768, intermediate=3072.
# Sets 1-3: β_override=0.25 (rectangular matrices, FFN or treated as rect)
# Sets 4-6: β_override=1.00 (square matrices, attention projections)
# Layers sampled: 0 (early), 5 (middle), 11 (final)
SETTINGS = [
    dict(name="encoder.layer.0.intermediate.dense.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=0.25, label="Set 1 — L0 FFN"),
    dict(name="encoder.layer.0.attention.self.query.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=0.25, label="Set 2 — L0 Att.Q"),
    dict(name="encoder.layer.5.attention.self.key.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=0.25, label="Set 3 — L5 Att.K"),
    dict(name="encoder.layer.5.output.dense.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=1.00, label="Set 4 — L5 Out"),
    dict(name="encoder.layer.11.intermediate.dense.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=1.00, label="Set 5 — L11 FFN"),
    dict(name="encoder.layer.11.attention.self.value.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=1.00, label="Set 6 — L11 Att.V"),
]

man_path = Path(WMP_DIR) / "manifest.json"
manifest = json.load(open(man_path))


# =============================================================================
# GRAPH 1 — Empirical PDF (ePDF) vs. conditional MP PDF
# =============================================================================
"""
Mosaic of six panels comparing normalised histograms of interior eigenvalues
against the conditional Marchenko-Pastur PDF.  Uses the helpers and SETTINGS
defined above; each panel has its own per-panel trim interval [L, U].

Output: graph_core_diag_01_bert_base.pdf  (1×6 subplot grid, 7×1 in)
"""

print("Building mosaic figure...")

fig, axes = plt.subplots(1, 6, figsize=(7, 1))
axes = axes.flatten()

for i, (ax, cfg) in enumerate(zip(axes, SETTINGS)):
    print(f"  [{i+1}/6] {cfg['label']}")
    entry = _find_manifest_entry(manifest, cfg["name"])
    W = _load_matrix(Path(WMP_DIR) / entry["path"]).astype(np.float64, copy=False)
    print(f"         shape=({W.shape[0]:.2e} x {W.shape[1]:.2e}), dtype={W.dtype}")

    lam_trim, (a, b, L, U, beta), mp_pdf_cond, _, N_trim = compute_trimmed(
        W, cfg["trim_kind"], cfg["c_tw"], cfg["frac_sq"], cfg["frac_rect"],
        beta_override=cfg.get("beta_override", None)
    )
    print(f"         beta={beta:.4e} | support=[{a:.4e}, {b:.4e}]")
    print(f"         trim=[{L:.4e}, {U:.4e}] | N_trim={N_trim:.2e}")

    x_grid = np.linspace(L, U, COND_GRID)

    if N_trim > 0:
        # Normalised histogram of interior eigenvalues
        ax.hist(lam_trim, bins=HIST_BINS, range=(L, U),
                density=True, alpha=0.4, color="#888888")

    # Conditional MP PDF curve
    ax.plot(x_grid, mp_pdf_cond(x_grid), color="black")

    # Vertical reference lines: light = full support edges, dark = trim edges
    for v, col in [(a,"#aaaaaa"),(b,"#aaaaaa"),(L,"#444444"),(U,"#444444")]:
        ax.axvline(v, color=col, linestyle="--", linewidth=0.8)

    ax.set_title(f"{cfg['label']} \n ($\\beta$={beta:.2f}, N={N_trim})", pad=2)
    ax.grid(True)

    if i != 0:
        ax.yaxis.set_ticklabels([])   # share y-axis label only on first panel

fig.text(-0.01, 0.5, "$\\lambda$ vs. PDF", va="center", rotation="vertical", fontsize=6)
plt.subplots_adjust(left=0.04, hspace=0.0, wspace=0.1)

pdf_path = "graph_core_diag_01_bert_base.pdf"
plt.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")


# =============================================================================
# GRAPH 2 — Empirical CDF (eCDF) vs. conditional MP CDF
# =============================================================================
"""
Reuses the helpers, manifest, and SETTINGS from the Graph 1 block.
Overlays the empirical step-CDF on the conditional MP CDF for each panel.

Output: graph_core_diag_02_bert_base.pdf  (1×6 subplot grid, 7×1 in)
"""

from matplotlib.lines import Line2D

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
    "mathtext.fontset": "stix",
    "font.size": 7, "axes.titlesize": 7, "axes.labelsize": 5,
    "xtick.labelsize": 5, "ytick.labelsize": 5, "legend.fontsize": 5,
    "axes.linewidth": 0.6, "lines.linewidth": 1.2,
    "grid.linewidth": 0.4, "grid.alpha": 0.3,
    "pdf.fonttype": 42, "ps.fonttype": 42,
})

print("Building mosaic figure...")

fig, axes = plt.subplots(1, 6, figsize=(7, 1))
axes = axes.flatten()

for i, (ax, cfg) in enumerate(zip(axes, SETTINGS)):
    print(f"  [{i+1}/6] {cfg['label']}")
    entry = _find_manifest_entry(manifest, cfg["name"])
    W = _load_matrix(Path(WMP_DIR) / entry["path"]).astype(np.float64, copy=False)
    print(f"         shape=({W.shape[0]:.2e} x {W.shape[1]:.2e}), dtype={W.dtype}")

    lam_trim, (a, b, L, U, beta), _, mp_cdf_cond, N_trim = compute_trimmed(
        W, cfg["trim_kind"], cfg["c_tw"], cfg["frac_sq"], cfg["frac_rect"],
        beta_override=cfg.get("beta_override", None)
    )
    print(f"         beta={beta:.4e} | support=[{a:.4e}, {b:.4e}]")
    print(f"         trim=[{L:.4e}, {U:.4e}] | N_trim={N_trim:.2e}")

    x_grid = np.linspace(L, U, COND_GRID)

    # Theoretical (conditional) MP CDF
    ax.plot(x_grid, mp_cdf_cond(x_grid), color="black")

    # Empirical step-CDF from sorted interior eigenvalues
    if N_trim > 0:
        y_ecdf = np.arange(1, N_trim + 1) / N_trim
        ax.step(lam_trim, y_ecdf, where="post", linewidth=1.0, color="#888888")

    for v, col in [(a,"#aaaaaa"),(b,"#aaaaaa"),(L,"#444444"),(U,"#444444")]:
        ax.axvline(v, color=col, linestyle="--", linewidth=0.8)

    ax.set_title(f"{cfg['label']} \n ($\\beta$={beta:.2f}, N={N_trim})", pad=2)
    ax.set_ylim(0, 1)
    ax.grid(True)

    if i != 0:
        ax.yaxis.set_ticklabels([])

handles = [
    Line2D([0], [0], color="black", linewidth=1.2, label="MP"),
    Line2D([0], [0], color="#888888", linewidth=1.0, drawstyle="steps-post", label="Empirical"),
]
axes[0].legend(handles=handles, loc="lower right", frameon=False)
fig.text(-0.01, 0.5, "$\\lambda$ vs. CDF", va="center", rotation="vertical", fontsize=6)
plt.subplots_adjust(left=0.04, hspace=0.0, wspace=0.3)

pdf_path = "graph_core_diag_02_bert_base.pdf"
plt.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")


# =============================================================================
# GRAPH 3 — ePDF vs. conditional MP PDF (shared global x-axis)
# =============================================================================
"""
Reuses the helpers, manifest, and SETTINGS from the Graph 1 block.
Like Graph 1 but all panels share a global x-axis [min(L), max(U)] computed
across all parameter sets, making spectral widths visually comparable.

Output: graph_core_diag_03_bert_base.pdf  (1×6 subplot grid, 7×1 in)
"""

from matplotlib.patches import Patch

COND_GRID   = 2000
HIST_BINS   = 120
GRID_POINTS = 8192

print("Building mosaic figure...")

# First pass: compute the global x range for cross-panel comparability
global_L, global_U = np.inf, -np.inf
for cfg in SETTINGS:
    entry = _find_manifest_entry(manifest, cfg["name"])
    W = _load_matrix(Path(WMP_DIR) / entry["path"]).astype(np.float64, copy=False)
    beta = cfg.get("beta_override") or min(W.shape) / max(W.shape)
    a, b = _mp_support(beta)
    delta = _edge_margin(beta, W.shape[0], W.shape[1],
                         cfg["trim_kind"], cfg["c_tw"], cfg["frac_sq"], cfg["frac_rect"])
    L, U = a + delta, b - delta
    if L >= U: L, U = a, b
    global_L, global_U = min(global_L, L), max(global_U, U)

fig, axes = plt.subplots(1, 6, figsize=(7, 1))
axes = axes.flatten()

for i, (ax, cfg) in enumerate(zip(axes, SETTINGS)):
    print(f"  [{i+1}/6] {cfg['label']}")
    entry = _find_manifest_entry(manifest, cfg["name"])
    W = _load_matrix(Path(WMP_DIR) / entry["path"]).astype(np.float64, copy=False)
    print(f"         shape=({W.shape[0]:.2e} x {W.shape[1]:.2e}), dtype={W.dtype}")

    lam_trim, (a, b, L, U, beta), mp_pdf_cond, _, N_trim = compute_trimmed(
        W, cfg["trim_kind"], cfg["c_tw"], cfg["frac_sq"], cfg["frac_rect"],
        beta_override=cfg.get("beta_override", None)
    )
    print(f"         beta={beta:.4e} | support=[{a:.4e}, {b:.4e}]")
    print(f"         trim=[{L:.4e}, {U:.4e}] | N_trim={N_trim:.2e}")

    # Use the global range so spectral widths are visually comparable
    x_grid = np.linspace(global_L, global_U, COND_GRID)

    if N_trim > 0:
        ax.hist(lam_trim, bins=HIST_BINS, range=(global_L, global_U),
                density=True, alpha=0.4, color="#888888")
    ax.plot(x_grid, mp_pdf_cond(x_grid), color="black")

    for v, col in [(a,"#aaaaaa"),(b,"#aaaaaa"),(L,"#444444"),(U,"#444444")]:
        ax.axvline(v, color=col, linestyle="--", linewidth=0.8)

    ax.set_title(f"{cfg['label']} \n ($\\beta$={beta:.2f}, N={N_trim})", pad=2)
    ax.grid(True)

    if i != 0:
        ax.yaxis.set_ticklabels([])

handles = [
    Line2D([0], [0], color="black", linewidth=1.2, label="MP"),
    Patch(facecolor="#888888", alpha=0.4, label="Empirical"),
]
axes[0].legend(handles=handles, loc="upper right", frameon=False)
fig.text(-0.01, 0.5, "$\\lambda$ vs. PDF", va="center", rotation="vertical", fontsize=6)
plt.subplots_adjust(left=0.04, hspace=0.0, wspace=0.3)

pdf_path = "graph_core_diag_03_bert_base.pdf"
plt.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")


# =============================================================================
# GRAPH 4 — Residual CDF (eCDF − conditional MP CDF)
# =============================================================================
"""
Self-contained section — redefines all helpers locally.
Plots the signed residual eCDF − MP_CDF for each of six parameter sets.
The KS statistic D_p = max|residual| is shown as dotted horizontal bands.
Shared y-axis enables direct comparison of fit quality across panels.

Output: graph_core_diag_04_bert_base.pdf  (1×6 subplot grid, 7×1 in)
"""

import re
import json
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
    "mathtext.fontset": "stix",
    "font.size": 7, "axes.titlesize": 7, "axes.labelsize": 5,
    "xtick.labelsize": 5, "ytick.labelsize": 5, "legend.fontsize": 5,
    "axes.linewidth": 0.6, "lines.linewidth": 1.2,
    "grid.linewidth": 0.4, "grid.alpha": 0.3,
    "pdf.fonttype": 42, "ps.fonttype": 42,
})

WMP_DIR     = "bert_weights_WMP"
GRID_POINTS = 8192
COND_GRID   = 2000

# Sets 1-3: β=0.25 | Sets 4-6: β=1.00
SETTINGS = [
    dict(name="encoder.layer.0.intermediate.dense.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=0.25, label="Set 1 — L0 FFN"),
    dict(name="encoder.layer.0.attention.self.query.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=0.25, label="Set 2 — L0 Att.Q"),
    dict(name="encoder.layer.5.attention.self.key.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=0.25, label="Set 3 — L5 Att.K"),
    dict(name="encoder.layer.5.output.dense.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=1.00, label="Set 4 — L5 Out"),
    dict(name="encoder.layer.11.intermediate.dense.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=1.00, label="Set 5 — L11 FFN"),
    dict(name="encoder.layer.11.attention.self.value.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=1.00, label="Set 6 — L11 Att.V"),
]

# ---- Local re-definitions of shared helpers (see Graph 1 block) ----
def _load_matrix(p: Path):
    if p.suffix == ".npy":  return np.load(p)
    if p.suffix == ".npz":  return np.load(p)["data"]
    raise ValueError(f"Unsupported file type: {p.suffix}")

def _mp_support(beta: float):
    r = np.sqrt(beta); return (1 - r)**2, (1 + r)**2

def _mp_pdf(x, beta, a, b):
    x = np.asarray(x, dtype=np.float64); out = np.zeros_like(x)
    m = (x >= a) & (x <= b); xm = np.clip(x[m], 1e-15, None)
    out[m] = np.sqrt((b - xm) * (xm - a)) / (2 * np.pi * beta * xm)
    return out

def _cumtrapz_np(y, x):
    dx = np.diff(x); seg = 0.5 * (y[:-1] + y[1:]) * dx
    return np.concatenate([[0.0], np.cumsum(seg)])

def _mp_cdf(x, beta, grid_points=GRID_POINTS):
    a, b = _mp_support(beta)
    t = np.linspace(0.0, 1.0, grid_points); g = a + (b - a) * t * t
    pdf = _mp_pdf(g, beta, a, b); cdf_vals = _cumtrapz_np(pdf, g)
    cdf_vals /= cdf_vals[-1]
    return np.interp(x, g, cdf_vals, left=0.0, right=1.0)

def _edge_margin(beta, m, n, trim_kind, c_tw, frac_sq, frac_rect):
    a, b = _mp_support(beta); bandwidth = b - a
    n_eff = min(m, n); is_square = (m == n)
    tw = (c_tw or 0) * (n_eff ** (-2/3)) * (1 + np.sqrt(beta))**(4/3)
    frac = (frac_sq if is_square else frac_rect) * bandwidth
    if trim_kind == "tw":             return tw
    if trim_kind == "fraction":       return frac
    if trim_kind == "tw_or_fraction": return max(tw, frac)
    raise ValueError("Invalid trim_kind")

def _find_manifest_entry(manifest, target):
    for e in manifest["files"]:
        if e.get("name","") == target: return e
    for e in manifest["files"]:
        if target in e.get("name","") or target in e.get("path",""): return e
    raise ValueError(f"Matrix '{target}' not found in manifest")

def compute_trimmed(W, TRIM_KIND, C_TW, EDGE_FRAC_SQUARE, EDGE_FRAC_RECT, beta_override=None):
    m, n = W.shape
    beta = beta_override if beta_override is not None else min(m, n) / max(m, n)
    s = np.linalg.svd(W, full_matrices=False, compute_uv=False)
    lambdas = (s**2) / max(m, n); lambdas.sort()
    a, b = _mp_support(beta)
    delta = _edge_margin(beta, m, n, TRIM_KIND, C_TW, EDGE_FRAC_SQUARE, EDGE_FRAC_RECT)
    L, U = a + delta, b - delta
    if L >= U: L, U = a, b
    mask = (lambdas >= L) & (lambdas <= U)
    lam_trim = lambdas[mask]; N_trim = lam_trim.size
    FL, FU = _mp_cdf([L, U], beta); den = max(FU - FL, 1e-12)
    # Graph 4 only needs the conditional CDF
    mp_cdf_cond = lambda x: np.clip((_mp_cdf(x, beta) - FL) / den, 0, 1)
    return lam_trim, (a, b, L, U, beta), mp_cdf_cond, N_trim

man_path = Path(WMP_DIR) / "manifest.json"
manifest = json.load(open(man_path))

print("Building mosaic figure...")

fig, axes = plt.subplots(1, 6, figsize=(7, 1), sharey=True)
axes = axes.flatten()

y_min, y_max = 0, 0   # track global residual range for unified y-axis

for i, (ax, cfg) in enumerate(zip(axes, SETTINGS)):
    print(f"  [{i+1}/6] {cfg['label']}")

    entry = _find_manifest_entry(manifest, cfg["name"])
    W = _load_matrix(Path(WMP_DIR) / entry["path"]).astype(np.float64, copy=False)
    print(f"         shape=({W.shape[0]:.2e} x {W.shape[1]:.2e}), dtype={W.dtype}")

    lam_trim, (a, b, L, U, beta), mp_cdf_cond, N_trim = compute_trimmed(
        W, cfg["trim_kind"], cfg["c_tw"], cfg["frac_sq"], cfg["frac_rect"],
        beta_override=cfg.get("beta_override", None)
    )
    print(f"         beta={beta:.4e} | support=[{a:.4e}, {b:.4e}]")
    print(f"         trim=[{L:.4e}, {U:.4e}] | N_trim={N_trim:.2e}")

    x_grid   = np.linspace(L, U, COND_GRID)
    # Empirical CDF on the same x-grid via sorted rank interpolation
    emp_cdf  = np.searchsorted(np.sort(lam_trim), x_grid, side="right") / max(N_trim, 1)
    residual = emp_cdf - mp_cdf_cond(x_grid)
    ks_stat  = np.max(np.abs(residual))   # Kolmogorov-Smirnov statistic D_p

    ax.plot(x_grid, residual, color="#444444", lw=1.2)
    ax.axhline(0,         color="black",   linestyle="--", linewidth=0.8)
    ax.axhline(+ks_stat,  color="#888888", linestyle=":",  linewidth=0.8)
    ax.axhline(-ks_stat,  color="#888888", linestyle=":",  linewidth=0.8)

    ax.set_title(f"{cfg['label']} \n ($\\beta$={beta:.2f}, KS={ks_stat:.3f})", pad=2)
    ax.grid(True)

    if i != 0:
        ax.yaxis.set_ticklabels([])

    y_min = min(y_min, residual.min())
    y_max = max(y_max, residual.max())

# Apply unified y-scale with 10 % padding
for ax in axes:
    ax.set_ylim(y_min * 1.1, y_max * 1.1)

handles = [
    Line2D([0], [0], color="#444444", linewidth=1.2, label="Residual"),
    Line2D([0], [0], color="black",   linewidth=0.8, linestyle="--", label="Zero"),
    Line2D([0], [0], color="#888888", linewidth=0.8, linestyle=":",  label="KS"),
]
axes[0].legend(handles=handles, loc="upper right", frameon=False)
fig.text(-0.01, 0.5, "Residual CDF", va="center", rotation="vertical", fontsize=6)
plt.subplots_adjust(left=0.04, hspace=0.0, wspace=0.3)

pdf_path = "graph_core_diag_04_bert_base.pdf"
plt.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")


# =============================================================================
# GRAPH 5 — Quantile-Quantile (QQ) plots of empirical vs. MP quantiles
# =============================================================================
"""
Self-contained section — redefines all helpers locally.
Q-Q plots comparing sorted interior eigenvalues against theoretical MP quantiles
obtained by inverting the conditional MP CDF.  Points on the diagonal indicate
agreement with the MP hypothesis.

Output: graph_core_diag_05_bert_base.pdf  (1×6 subplot grid, 7×1 in)
"""

import json
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
    "mathtext.fontset": "stix",
    "font.size": 7, "axes.titlesize": 7, "axes.labelsize": 5,
    "xtick.labelsize": 5, "ytick.labelsize": 5, "legend.fontsize": 5,
    "axes.linewidth": 0.6, "lines.linewidth": 1.2,
    "grid.linewidth": 0.4, "grid.alpha": 0.3,
    "pdf.fonttype": 42, "ps.fonttype": 42,
})

WMP_DIR     = "bert_weights_WMP"
GRID_POINTS = 8192
COND_GRID   = 2000

# Sets 1-3: β=0.25 | Sets 4-6: β=1.00
SETTINGS = [
    dict(name="encoder.layer.0.intermediate.dense.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=0.25, label="Set 1 — L0 FFN"),
    dict(name="encoder.layer.0.attention.self.query.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=0.25, label="Set 2 — L0 Att.Q"),
    dict(name="encoder.layer.5.attention.self.key.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=0.25, label="Set 3 — L5 Att.K"),
    dict(name="encoder.layer.5.output.dense.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=1.00, label="Set 4 — L5 Out"),
    dict(name="encoder.layer.11.intermediate.dense.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=1.00, label="Set 5 — L11 FFN"),
    dict(name="encoder.layer.11.attention.self.value.weight_WMP",
         trim_kind="tw_or_fraction", c_tw=2.0, frac_sq=0.05, frac_rect=0.05,
         beta_override=1.00, label="Set 6 — L11 Att.V"),
]

# ---- Local re-definitions (see Graph 1 block for docstrings) ----
def _load_matrix(p: Path):
    if p.suffix == ".npy":  return np.load(p)
    if p.suffix == ".npz":  return np.load(p)["data"]
    raise ValueError(f"Unsupported file type: {p.suffix}")

def _mp_support(beta: float):
    r = np.sqrt(beta); return (1 - r)**2, (1 + r)**2

def _mp_pdf(x, beta, a, b):
    x = np.asarray(x, dtype=np.float64); out = np.zeros_like(x)
    m = (x >= a) & (x <= b); xm = np.clip(x[m], 1e-15, None)
    out[m] = np.sqrt((b - xm) * (xm - a)) / (2 * np.pi * beta * xm)
    return out

def _cumtrapz_np(y, x):
    dx = np.diff(x); seg = 0.5 * (y[:-1] + y[1:]) * dx
    return np.concatenate([[0.0], np.cumsum(seg)])

def _mp_cdf(x, beta, grid_points=GRID_POINTS):
    a, b = _mp_support(beta)
    t = np.linspace(0.0, 1.0, grid_points); g = a + (b - a) * t * t
    pdf = _mp_pdf(g, beta, a, b); cdf_vals = _cumtrapz_np(pdf, g)
    cdf_vals /= cdf_vals[-1]
    return np.interp(x, g, cdf_vals, left=0.0, right=1.0)

def _edge_margin(beta, m, n, trim_kind, c_tw, frac_sq, frac_rect):
    a, b = _mp_support(beta); bandwidth = b - a
    n_eff = min(m, n); is_square = (m == n)
    tw = c_tw * (n_eff ** (-2/3)) * (1 + np.sqrt(beta))**(4/3)
    frac = (frac_sq if is_square else frac_rect) * bandwidth
    if trim_kind == "tw":             return tw
    if trim_kind == "fraction":       return frac
    if trim_kind == "tw_or_fraction": return max(tw, frac)
    raise ValueError("Invalid trim_kind")

def _find_manifest_entry(manifest, target):
    for e in manifest["files"]:
        if e.get("name","") == target: return e
    for e in manifest["files"]:
        if target in e.get("name","") or target in e.get("path",""): return e
    raise ValueError(f"Matrix '{target}' not found in manifest")

def compute_trimmed(W, TRIM_KIND, C_TW, EDGE_FRAC_SQUARE, EDGE_FRAC_RECT, beta_override=None):
    m, n = W.shape
    beta = beta_override if beta_override is not None else min(m, n) / max(m, n)
    s = np.linalg.svd(W, full_matrices=False, compute_uv=False)
    lambdas = (s**2) / max(m, n); lambdas.sort()
    a, b = _mp_support(beta)
    delta = _edge_margin(beta, m, n, TRIM_KIND, C_TW, EDGE_FRAC_SQUARE, EDGE_FRAC_RECT)
    L, U = a + delta, b - delta
    if L >= U: L, U = a, b
    mask = (lambdas >= L) & (lambdas <= U)
    lam_trim = lambdas[mask]; N_trim = lam_trim.size
    FL, FU = _mp_cdf([L, U], beta); den = max(FU - FL, 1e-12)
    mp_cdf_cond = lambda x: np.clip((_mp_cdf(x, beta) - FL) / den, 0, 1)
    return lam_trim, (a, b, L, U, beta), mp_cdf_cond, N_trim

manifest = json.load(open(Path(WMP_DIR) / "manifest.json"))

print("Building mosaic figure...")

fig, axes = plt.subplots(1, 6, figsize=(7, 1), sharex=True, sharey=True)
axes = axes.flatten()

for i, (ax, cfg) in enumerate(zip(axes, SETTINGS)):
    print(f"  [{i+1}/6] {cfg['label']}")

    entry = _find_manifest_entry(manifest, cfg["name"])
    W = _load_matrix(Path(WMP_DIR) / entry["path"]).astype(np.float64, copy=False)
    print(f"         shape=({W.shape[0]:.2e} x {W.shape[1]:.2e}), dtype={W.dtype}")

    lam_trim, (a, b, L, U, beta), mp_cdf_cond, N_trim = compute_trimmed(
        W, cfg["trim_kind"], cfg["c_tw"], cfg["frac_sq"], cfg["frac_rect"],
        beta_override=cfg.get("beta_override", None)
    )
    print(f"         beta={beta:.4e} | support=[{a:.4e}, {b:.4e}]")
    print(f"         trim=[{L:.4e}, {U:.4e}] | N_trim={N_trim:.2e}")

    emp_q  = np.sort(lam_trim)                # empirical quantiles
    q_grid = np.linspace(0, 1, N_trim)        # probability levels
    xs     = np.linspace(L, U, COND_GRID)
    # Invert the conditional MP CDF to obtain theoretical quantiles
    mp_q   = np.interp(q_grid, mp_cdf_cond(xs), xs)

    ax.plot(mp_q, emp_q, "o", ms=1.5, alpha=0.5, color="#888888")
    # Diagonal reference line: perfect MP agreement
    ax.plot([mp_q.min(), mp_q.max()], [mp_q.min(), mp_q.max()],
            color="black", linestyle="--", linewidth=0.8)

    ax.set_title(f"{cfg['label']} \n ($\\beta$={beta:.2f}, N={N_trim})", pad=2)
    ax.grid(True)

    if i != 0:
        ax.yaxis.set_ticklabels([])

handles = [
    Line2D([0], [0], marker="o", color="none", markerfacecolor="#888888",
           markersize=3, alpha=0.5, label="Empirical"),
    Line2D([0], [0], color="black", linewidth=0.8, linestyle="--", label="MP"),
]
axes[0].legend(handles=handles, loc="lower right", frameon=False)
fig.text(-0.01, 0.5, "MP vs. Empirical quantiles", va="center",
         rotation="vertical", fontsize=6)
plt.subplots_adjust(left=0.04, hspace=0.0, wspace=0.3)

pdf_path = "graph_core_diag_05_bert_base.pdf"
plt.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")


# =============================================================================
# GRAPH 6 — Layer × Matrix-type heatmaps of KS acceptance decisions
# =============================================================================
"""
Two-row heatmap mosaic of binary accept/reject decisions for six analysis
configurations, under KS-strict (row 0) and KS-TW (row 1).

BERT-base-specific: decisions shape is (12, 6) — 12 layers, 6 matrix types.
Layer-tick density is thinned to every 3rd layer (``int(t) % 3 == 0``)
to avoid crowding on the 12-row heatmaps.
The legend is commented out; uncomment to re-enable.

Output: graph_level_views_01_bert_base.pdf  (2×6 subplot grid, 7×3 in)
"""

import seaborn as sns
from matplotlib.patches import Patch

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
    "mathtext.fontset": "stix",
    "font.size": 7, "axes.titlesize": 7, "axes.labelsize": 5,
    "xtick.labelsize": 5, "ytick.labelsize": 5, "legend.fontsize": 5,
    "axes.linewidth": 0.6, "lines.linewidth": 1.2,
    "grid.linewidth": 0.4, "grid.alpha": 0.3,
    "pdf.fonttype": 42, "ps.fonttype": 42,
})

GRAY_CMAP  = "Greys"
VMIN, VMAX = 0.1, 0.6


def plot_ks_mosaic_separate(decisions_strict: np.ndarray,
                             decisions_tw: np.ndarray,
                             savepath: str = "graph_level_views_01_bert_base.pdf"):
    """
    Render a 2×6 heatmap mosaic of per-layer KS decisions for BERT-base.

    Each column corresponds to one analysis parameter set (different α or
    layer/type subset).  BERT-base has 12 layers; y-ticks are shown every
    3rd layer to avoid visual crowding.

    Parameters
    ----------
    decisions_strict : np.ndarray, shape (12, 6)
        Binary matrix for the standard KS criterion: 0 = accept, 1 = reject.
    decisions_tw : np.ndarray, shape (12, 6)
        Binary matrix for the KS-TW criterion.
    savepath : str
        Destination PDF path.

    Side effects
    ------------
    Saves a PDF to ``savepath`` and displays the figure.
    """
    # BERT-base: 12 layers, 6 matrix types
    # Set 3 covers only the first 6 layers; Set 4 covers the last 6 layers
    param_sets = [
        dict(alpha=0.01, layers=list(range(12)),
             mat_types=["Q","K","V","Att-Out","FFN-In","FFN-Out"],
             title="Set 1 — $\\alpha$=0.01"),
        dict(alpha=0.05, layers=list(range(12)),
             mat_types=["Q","K","V","Att-Out","FFN-In","FFN-Out"],
             title="Set 2 — $\\alpha$=0.05"),
        dict(alpha=0.10, layers=list(range(6)),
             mat_types=["Q","K","V","Att-Out","FFN-In","FFN-Out"],
             title="Set 3 — $\\alpha$=0.10"),
        dict(alpha=0.20, layers=list(range(6, 12)),
             mat_types=["Q","K","V","Att-Out","FFN-In","FFN-Out"],
             title="Set 4 — $\\alpha$=0.20"),
        dict(alpha=0.05, layers=list(range(12)),
             mat_types=["Q","K","V","Att-Out","FFN-In","FFN-Out"],
             title="Set 5 — $\\alpha$=0.05"),
        dict(alpha=0.05, layers=list(range(4)),
             mat_types=["Q","K","V"],
             title="Set 6 — $\\alpha$=0.05"),
    ]

    print("Building mosaic figure...")
    fig, axes = plt.subplots(2, 6, figsize=(7, 3))

    for idx, params in enumerate(param_sets):
        print(f"  [{idx+1}/6] {params['title']}")

        L     = params["layers"]
        M     = params["mat_types"]
        title = params["title"]

        d_strict = decisions_strict[np.ix_(L, range(min(len(M), decisions_strict.shape[1])))]
        d_tw     = decisions_tw[np.ix_(L,     range(min(len(M), decisions_tw.shape[1])))]

        # Map binary decisions to gray intensity values
        d_strict_gs = np.where(d_strict == 0, VMIN, VMAX)
        d_tw_gs     = np.where(d_tw     == 0, VMIN, VMAX)

        ax_strict = axes[0, idx]
        ax_tw     = axes[1, idx]

        # ---- KS-strict heatmap (top row) ----
        sns.heatmap(d_strict_gs, cmap=GRAY_CMAP, vmin=0, vmax=1,
                    cbar=False, annot=False,
                    xticklabels=M, yticklabels=L, ax=ax_strict)
        ax_strict.set_title(f"{title}\nKS Strict", pad=2)
        ax_strict.set_xticklabels(ax_strict.get_xticklabels(), rotation=45, ha="right")

        # Thin y-ticks to every 3rd layer to avoid crowding on 12-row heatmaps
        yticks      = [t for t in ax_strict.get_yticks() if int(t) % 3 == 0]
        yticklabels = [str(L[int(t)]) for t in yticks if int(t) < len(L)]
        ax_strict.set_yticks(yticks)
        ax_strict.set_yticklabels(yticklabels, rotation=0)

        if idx == 0:
            ax_strict.set_ylabel("Layer")
            ax_strict.yaxis.set_label_coords(-0.35, 0.5)
        else:
            ax_strict.set_ylabel("")
            ax_strict.yaxis.set_visible(False)

        # ---- KS-TW heatmap (bottom row) ----
        sns.heatmap(d_tw_gs, cmap=GRAY_CMAP, vmin=0, vmax=1,
                    cbar=False, annot=False,
                    xticklabels=M, yticklabels=False, ax=ax_tw)
        ax_tw.set_title(f"{title}\nKS–TW", pad=2)
        ax_tw.set_xticklabels(ax_tw.get_xticklabels(), rotation=45, ha="right")

        if idx == 0:
            ax_tw.set_ylabel("Layer")
            ax_tw.yaxis.set_label_coords(-0.35, 0.5)
        else:
            ax_tw.set_ylabel("")
            ax_tw.yaxis.set_visible(False)

    # Legend commented out for compactness — uncomment to re-enable
    # handles = [
    #     Patch(facecolor=plt.cm.Greys(VMIN), label="Accept"),
    #     Patch(facecolor=plt.cm.Greys(VMAX), label="Reject"),
    # ]
    # fig.legend(handles=handles, loc="lower center", ncol=2,
    #            frameon=False, bbox_to_anchor=(0.5, -0.02))

    plt.subplots_adjust(left=0.04, hspace=0.8, wspace=0.3)

    plt.savefig(savepath, format="pdf", bbox_inches="tight")
    print(f"PDF saved: {savepath}")
    plt.show()
    plt.close()
    print("Done.")


# ---- Mock decision arrays (replace with real KS outputs in practice) ----
# BERT-base: 12 layers, 6 matrix types → shape (12, 6)
np.random.seed(42)
decisions_strict = np.random.choice([0, 1], size=(12, 6), p=[0.4, 0.6])
decisions_tw     = np.random.choice([0, 1], size=(12, 6), p=[0.3, 0.7])

plot_ks_mosaic_separate(decisions_strict, decisions_tw,
                        savepath="graph_level_views_01_bert_base.pdf")


# =============================================================================
# GRAPH 7 — Per-layer acceptance rates under KS-strict and KS-TW
# =============================================================================
"""
Line plots showing mean acceptance rate ± Wilson 95 % CI per layer across
three α levels and six scenario functions.

BERT-base-specific: 12 layers (0-11); the ``scenario_square_vs_rect``
split is at layer 6 (halfway), unlike BERT-Large which splits at 12.
The ``scenario_mixed_g10`` variant used in Graph 10 (``layers 0-5 vs. 6-11``)
follows the same convention.

Output: graph_level_views_02_bert_base.pdf  (6×3 subplot grid, 7×5 in)
"""

from statsmodels.stats.proportion import proportion_confint

METHOD_COLORS = ["#444444", "#aaaaaa"]

# BERT-base: 12 encoder layers
layers  = np.arange(12)
alphas  = [0.01, 0.05, 0.10]
methods = ["KS-strict", "KS-TW"]
n_boot  = 50
rng     = np.random.default_rng(42)


def scenario_baseline(layer, method, alpha):
    """Constant acceptance probability across all layers."""
    return 0.55 if method == "KS-strict" else 0.65


def scenario_strict_dominance(layer, method, alpha):
    """KS-strict consistently more accepting than KS-TW."""
    return 0.75 if method == "KS-strict" else 0.90


def scenario_low_alpha(layer, method, alpha):
    """Strong α-sensitivity: very few acceptances at α=0.01."""
    if alpha == 0.01:
        return 0.15 if method == "KS-strict" else 0.35
    elif alpha == 0.05:
        return 0.45 if method == "KS-strict" else 0.55
    else:
        return 0.75 if method == "KS-strict" else 0.80


def scenario_square_vs_rect(layer, method, alpha):
    """
    Layer-dependent split at 6 (BERT-base midpoint):
    layers 0-5 (square attention) are well-fitted;
    layers 6-11 (rectangular FFN) are poorly fitted.
    """
    if layer < 6:
        return 0.80 if method == "KS-strict" else 0.90
    else:
        return 0.30 if method == "KS-strict" else 0.50


def scenario_edge_sensitive(layer, method, alpha):
    """Alternating acceptance by layer index; KS-TW is uniformly accepting."""
    if method == "KS-strict":
        return 0.40 + 0.20 * (layer % 2)
    else:
        return 0.70


def scenario_extreme_disagreement(layer, method, alpha):
    """Extreme divergence: KS-strict almost always rejects, KS-TW accepts."""
    return 0.12 if method == "KS-strict" else 0.87


SCENARIOS = {
    "Baseline":              scenario_baseline,
    "Strict dominance":      scenario_strict_dominance,
    "Low $\\alpha$ effect":  scenario_low_alpha,
    "Square vs rect":        scenario_square_vs_rect,
    "Edge-sensitive":        scenario_edge_sensitive,
    "Extreme disag.":        scenario_extreme_disagreement,
}

print("Building mosaic figure...")

fig, axes = plt.subplots(len(SCENARIOS), len(alphas),
                         figsize=(7, 5), sharey=True)
axes = np.array(axes)

x        = np.arange(len(layers))
last_row = len(SCENARIOS) - 1
last_lay = len(layers) - 1

for row, (name, func) in enumerate(SCENARIOS.items()):
    print(f"  [{row+1}/6] {name}")

    decisions = np.zeros((len(layers), len(methods), len(alphas), n_boot))
    for i, layer in enumerate(layers):
        for j, method in enumerate(methods):
            for k, alpha in enumerate(alphas):
                p = func(layer, methods[j], alphas[k])
                decisions[i,j,k,:] = rng.choice([0,1], size=n_boot, p=[1-p, p])

    accept_means = np.mean(decisions, axis=-1)
    ci_low  = np.zeros_like(accept_means)
    ci_high = np.zeros_like(accept_means)

    for i in range(len(layers)):
        for j in range(len(methods)):
            for k in range(len(alphas)):
                count = np.sum(decisions[i,j,k,:])
                low, high = proportion_confint(count, n_boot, alpha=0.05, method="wilson")
                ci_low[i,j,k]  = low
                ci_high[i,j,k] = high

    for k, alpha in enumerate(alphas):
        ax = axes[row, k]

        for j, method in enumerate(methods):
            ax.plot(x, accept_means[:,j,k],
                    marker="o", ms=1.5, linewidth=0.6,
                    color=METHOD_COLORS[j],
                    label=method if (row == last_row and k == 0) else None)
            ax.fill_between(x, ci_low[:,j,k], ci_high[:,j,k],
                            alpha=0.2, color=METHOD_COLORS[j])

        if row == 0:
            ax.set_title(f"$\\alpha$ = {alpha}", pad=2)

        if row == last_row:
            ax.set_xlabel("Layer")

        # Show only first and last layer tick to reduce clutter
        ax.set_xticks([0, last_lay])
        ax.set_xticklabels([str(layers[0]), str(layers[last_lay])])
        ax.set_ylim(0, 1)
        ax.grid(True, axis="y")

        if k == 0:
            ax.set_ylabel("AccRate")
            ax.yaxis.set_label_coords(-0.20, 0.5)
            ax.text(-0.28, 0.5, name, va="center", ha="right",
                    rotation=90, transform=ax.transAxes, fontsize=5)
        else:
            ax.set_ylabel("")

axes[last_row, 0].legend(title="Method", frameon=False)
plt.subplots_adjust(hspace=0.35, wspace=0.2)

pdf_path = "graph_level_views_02_bert_base.pdf"
fig.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")


# =============================================================================
# GRAPH 8 — Aspect ratio β vs. KS statistic (D_p) scatter
# =============================================================================
"""
Scatter plot of β against D_p for simulated Attention and FFN matrix families
across six simulation scenarios.

BERT-base β clusters:
* Attention (Q/K/V/output, 768×768): β ≈ 1.0
* FFN (3072×768 or 768×3072):        β ≈ 0.25

Output: graph_level_views_03_bert_base.pdf  (1×6 subplot grid, 7×1 in)
"""

FAMILY_COLORS = {"FFN": "#888888", "Attention": "#111111"}


def generate_data_scenario(scenario: str, n_points: int = 50):
    """
    Generate synthetic (β, D_p, family) data for a named simulation scenario.

    BERT-base β clusters:
    * Attention: β ∈ [0.95, 1.0]
    * FFN:       β ∈ [0.20, 0.30]

    Parameters
    ----------
    scenario : str
        One of ``"baseline"``, ``"strict"``, ``"edge"``, ``"lowalpha"``,
        ``"smooth"``, ``"mixed"``.
    n_points : int
        Total number of data points.

    Returns
    -------
    betas, ks_vals, fams : np.ndarray
        Arrays of shape (n_points,).
    """
    np.random.seed(42)
    betas, ks_vals, fams = [], [], []

    if scenario == "baseline":
        # Balanced moderate D_p for both families
        for _ in range(n_points):
            if np.random.rand() < 0.67:
                beta = np.random.uniform(0.95, 1.0); fam = "Attention"
                ks   = np.random.uniform(0.05, 0.15)
            else:
                beta = np.random.uniform(0.20, 0.30); fam = "FFN"
                ks   = np.random.uniform(0.08, 0.20)
            betas.append(beta); ks_vals.append(ks); fams.append(fam)

    elif scenario == "strict":
        # FFN has clearly higher D_p (worse fit to MP)
        for _ in range(n_points):
            if np.random.rand() < 0.67:
                beta = np.random.uniform(0.95, 1.0); fam = "Attention"
                ks   = np.random.uniform(0.05, 0.10)
            else:
                beta = np.random.uniform(0.20, 0.30); fam = "FFN"
                ks   = np.random.uniform(0.30, 0.45)
            betas.append(beta); ks_vals.append(ks); fams.append(fam)

    elif scenario == "edge":
        # FFN D_p has high variance (spectral edge sensitivity)
        for _ in range(n_points):
            if np.random.rand() < 0.67:
                beta = np.random.uniform(0.95, 1.0); fam = "Attention"
                ks   = np.random.uniform(0.05, 0.15)
            else:
                beta = np.random.uniform(0.20, 0.30); fam = "FFN"
                ks   = np.random.uniform(0.20, 0.60)
            betas.append(beta); ks_vals.append(ks); fams.append(fam)

    elif scenario == "lowalpha":
        # Both families have elevated D_p (stringent test)
        for _ in range(n_points):
            if np.random.rand() < 0.67:
                beta = np.random.uniform(0.95, 1.0); fam = "Attention"
                ks   = np.random.uniform(0.15, 0.25)
            else:
                beta = np.random.uniform(0.20, 0.30); fam = "FFN"
                ks   = np.random.uniform(0.30, 0.50)
            betas.append(beta); ks_vals.append(ks); fams.append(fam)

    elif scenario == "smooth":
        # Both families tightly clustered around low D_p values
        for _ in range(n_points):
            if np.random.rand() < 0.67:
                beta = np.random.uniform(0.95, 1.0); fam = "Attention"
                ks   = np.random.normal(0.08, 0.005)
            else:
                beta = np.random.uniform(0.20, 0.30); fam = "FFN"
                ks   = np.random.normal(0.18, 0.005)
            betas.append(beta); ks_vals.append(ks); fams.append(fam)

    elif scenario == "mixed":
        # Reversed pattern: Attention has higher D_p than FFN
        for i in range(n_points):
            if i < n_points // 2:
                beta = np.random.uniform(0.95, 1.0)
                ks   = np.random.normal(0.25, 0.02); fam = "Attention"
            else:
                beta = np.random.uniform(0.20, 0.30)
                ks   = np.random.normal(0.10, 0.02); fam = "FFN"
            betas.append(beta); ks_vals.append(ks); fams.append(fam)

    return np.array(betas), np.array(ks_vals), np.array(fams)


scenarios = {
    "baseline": "Baseline balanced",
    "strict":   "Strict dominance",
    "edge":     "Edge-sensitive",
    "lowalpha": "Low $\\alpha$ test",
    "smooth":   "Smooth trimming",
    "mixed":    "Mixed block structure",
}

print("Building mosaic figure...")

fig, axes = plt.subplots(1, 6, figsize=(7, 1), sharex=True, sharey=True)
axes = axes.flatten()

for i, (ax, (key, title)) in enumerate(zip(axes, scenarios.items())):
    print(f"  [{i+1}/6] {title}")

    betas, ks_vals, fams = generate_data_scenario(key, n_points=60)

    for fam in np.unique(fams):
        idx = fams == fam
        ax.scatter(betas[idx], ks_vals[idx],
                   alpha=0.6, s=4, color=FAMILY_COLORS[fam], linewidths=0)

    # Vertical lines at the two BERT-base β clusters
    ax.axvline(1.0,  color="#aaaaaa", ls=":", linewidth=0.6, alpha=0.5)
    ax.axvline(0.25, color="#888888", ls=":", linewidth=0.6, alpha=0.5)
    # Horizontal threshold lines
    ax.axhline(0.1, color="#aaaaaa", ls="--", linewidth=0.8)
    ax.axhline(0.2, color="#aaaaaa", ls="--", linewidth=0.8)

    ax.set_title(f"{title}", pad=2)
    ax.grid(True)

    if i != 0:
        ax.yaxis.set_ticklabels([])

handles = [
    Line2D([0], [0], marker="o", color="none", markerfacecolor="#111111",
           markersize=3, alpha=0.6, label="Attention"),
    Line2D([0], [0], marker="o", color="none", markerfacecolor="#888888",
           markersize=3, alpha=0.6, label="FFN"),
]
axes[0].legend(handles=handles, loc="upper right", frameon=False)
fig.text(0.0, 0.5, r"$\beta$ vs. $D_{p}$", va="center",
         rotation="vertical", fontsize=6)
plt.subplots_adjust(left=0.04, hspace=0.0, wspace=0.3)

pdf_path = "graph_level_views_03_bert_base.pdf"
plt.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")


# =============================================================================
# GRAPH 9 — Bootstrap p-value distributions across calibration scenarios
# =============================================================================
"""
Line plots of binned p-value histograms for KS-strict and KS-TW across six
simulation scenarios.  Under H₀ the p-value distribution should be uniform
on [0, 1]; deviations indicate anti-conservatism or conservatism.

Note: the scenario dict is named ``SCENARIOS_P`` here to avoid shadowing the
``SCENARIOS`` dict defined for Graph 7 in the same module scope.

Output: graph_shrinkage_control_01_bert_base.pdf  (1×6 subplot grid, 7×1 in)
"""

METHOD_COLORS = {"KS-strict": "#444444", "KS-TW": "#aaaaaa"}

n_boot = 1000


def simulate_pvalues(null: bool = True, skew: float = 0.0,
                     conservative: bool = False, seed=None) -> np.ndarray:
    """
    Generate simulated p-values for calibration diagnostics.

    Parameters
    ----------
    null : bool
        ``True`` → Uniform[0,1] (correct null).
        ``False`` → Beta(0.7, 1.0) (anti-conservative, excess small p-values).
    skew : float
        Right-skew via ``p → p^{1+skew}``.  Positive pushes mass toward 0.
    conservative : bool
        ``True`` → ``p → 1 − (1−p)²`` pushes mass toward 1.
    seed : int or None
        RNG seed for reproducibility.

    Returns
    -------
    np.ndarray, shape (n_boot,)
        Simulated p-values clipped to [0, 1].
    """
    rng = np.random.default_rng(seed)
    if null:
        pvals = rng.random(n_boot)
    else:
        pvals = rng.beta(0.7, 1.0, size=n_boot)
    if skew > 0:
        pvals = np.power(pvals, 1 + skew)
    if conservative:
        pvals = 1 - np.power(1 - pvals, 2)
    return np.clip(pvals, 0, 1)


# Named ``SCENARIOS_P`` to avoid shadowing the Graph 7 SCENARIOS dict
SCENARIOS_P = {
    "Null calibration":   (simulate_pvalues(null=True,  seed=1),
                           simulate_pvalues(null=True,  seed=2)),
    "Anti-cons. strict":  (simulate_pvalues(null=False, seed=3),
                           simulate_pvalues(null=True,  seed=4)),
    "Conservative TW":    (simulate_pvalues(null=True,  seed=5),
                           simulate_pvalues(null=True,  conservative=True, seed=6)),
    "Both anti-cons.":    (simulate_pvalues(null=False, seed=7),
                           simulate_pvalues(null=False, seed=8)),
    "Skewed strict":      (simulate_pvalues(null=True,  skew=0.5, seed=9),
                           simulate_pvalues(null=True,  seed=10)),
    "Mixed calibration":  (simulate_pvalues(null=True,  conservative=True, seed=11),
                           simulate_pvalues(null=False, seed=12)),
}

print("Building mosaic figure...")

fig, axes = plt.subplots(1, 6, figsize=(7, 1), sharex=True, sharey=True)
axes = axes.flatten()

bins    = np.linspace(0, 1, 21)
centers = 0.5 * (bins[:-1] + bins[1:])

for i, (ax, (title, (pvals_strict, pvals_tw))) in enumerate(zip(axes, SCENARIOS_P.items())):
    print(f"  [{i+1}/6] {title}")

    for pvals, label in [(pvals_strict, "KS-strict"), (pvals_tw, "KS-TW")]:
        color = METHOD_COLORS[label]
        counts, _ = np.histogram(pvals, bins=bins)
        ax.plot(centers, counts, marker="o", ms=1.5, linewidth=0.6, color=color)
        ax.fill_between(centers, counts, alpha=0.15, color=color)

    ax.set_title(title, pad=2)
    ax.set_xlim(0, 1)
    ax.set_ylim(0, n_boot // 5)
    ax.grid(True)

    if i != 0:
        ax.yaxis.set_ticklabels([])

handles = [
    Line2D([0], [0], color="#444444", linewidth=0.8, marker="o",
           markersize=2, label="KS-strict"),
    Line2D([0], [0], color="#aaaaaa", linewidth=0.8, marker="o",
           markersize=2, label="KS-TW"),
]
axes[0].legend(handles=handles, loc="upper right", frameon=False)
fig.text(0.0, 0.5, "p-value vs. Frequency", va="center",
         rotation="vertical", fontsize=6)
plt.subplots_adjust(left=0.04, hspace=0.0, wspace=0.3)

pdf_path = "graph_shrinkage_control_01_bert_base.pdf"
plt.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")


# =============================================================================
# GRAPH 10 — Sensitivity of KS-TW outcomes to edge relaxation parameter c_α
# =============================================================================
"""
Line plots of per-layer KS statistic D_p as a function of c_α ∈ {1, 2, 3}
for six scenario families.

BERT-base-specific:
* 12 layers (``layers_g10 = list(range(12))``).
* ``scenario_mixed_g10`` splits at layer 6 (halfway), not layer 12.
* Scenario variables are suffixed ``_g10`` and ``_G10`` to avoid shadowing
  the identically-named functions defined for Graph 7.

Output: graph_shrinkage_control_02_bert_base.pdf  (1×6 subplot grid, 7×1 in)
"""

np.random.seed(42)
layers_g10  = list(range(12))   # BERT-base: 12 layers
c_TW_values = [1, 2, 3]
thresholds  = [0.10, 0.12, 0.15]


def scenario_stable_accept(layer, c):
    """D_p uniformly low: consistently accepted regardless of c."""
    return np.random.uniform(0.05, 0.08)


def scenario_relax_accept(layer, c):
    """D_p decreases as c increases (larger trim → better interior fit)."""
    return 0.20 / c + np.random.uniform(-0.02, 0.02)


def scenario_persistent_reject(layer, c):
    """D_p uniformly high: none of the layers follow the MP law."""
    return np.random.uniform(0.18, 0.25)


def scenario_mixed_g10(layer, c):
    """
    Split at layer 6 (BERT-base midpoint):
    layers 0-5 are c-sensitive; layers 6-11 are robustly low.
    """
    if layer < 6:
        return 0.20 / c
    else:
        return np.random.uniform(0.08, 0.10)


def scenario_edgesensitive(layer, c):
    """D_p oscillates with c via a sinusoidal pattern (edge artefact)."""
    return 0.12 + 0.05 * np.sin(0.5 * np.pi * c) \
                + np.random.uniform(-0.01, 0.01)


def scenario_alpha_dependent(layer, c):
    """D_p decreases with c; multiple α thresholds shown."""
    return 0.20 / c + np.random.uniform(-0.02, 0.02)


# Suffixed ``_G10`` to avoid shadowing the Graph 7 SCENARIOS dict
SCENARIOS_G10 = [
    ("Stable accept.",          scenario_stable_accept),
    ("Strict→Relax accept.",    scenario_relax_accept),
    ("Persistent rejection",    scenario_persistent_reject),
    ("Mixed families",          scenario_mixed_g10),
    ("Edge-sensitive",          scenario_edgesensitive),
    ("$\\alpha$-dependent",     scenario_alpha_dependent),
]

print("Building mosaic figure...")

fig, axes = plt.subplots(1, 6, figsize=(7, 1), sharex=True, sharey=True)
axes = axes.flatten()

for i, (ax, (title, func)) in enumerate(zip(axes, SCENARIOS_G10)):
    print(f"  [{i+1}/6] {title}")

    # D_p matrix: rows = layers, cols = c_TW values
    D_trim = np.zeros((len(layers_g10), len(c_TW_values)))
    for j, c in enumerate(c_TW_values):
        for layer in range(len(layers_g10)):
            D_trim[layer, j] = func(layer, c)

    # One line per layer drawn in the same gray to show ensemble spread
    for layer in range(len(layers_g10)):
        ax.plot(c_TW_values, D_trim[layer, :],
                marker="o", ms=1.5, alpha=0.5, linewidth=0.6, color="#888888")

    # Threshold reference line(s)
    if title == "$\\alpha$-dependent":
        for th in thresholds:
            ax.axhline(th, linestyle="--", color="#444444", linewidth=0.8, alpha=0.6)
    else:
        ax.axhline(0.12, linestyle="--", color="#444444", linewidth=0.8, alpha=0.6)

    ax.set_title(title, pad=2)
    ax.set_xticks(c_TW_values)
    ax.grid(True)

    if i != 0:
        ax.yaxis.set_ticklabels([])

handles = [
    Line2D([0], [0], color="#888888", linewidth=0.6, marker="o",
           markersize=2, alpha=0.5, label="Layer"),
    Line2D([0], [0], color="#444444", linewidth=0.8, linestyle="--",
           alpha=0.6, label="Threshold"),
]
axes[0].legend(handles=handles, loc="upper right", frameon=False)
fig.text(0, 0.5, r"$c_{\alpha}$ vs. $D_{p}$", va="center",
         rotation="vertical", fontsize=6)
plt.subplots_adjust(left=0.04, hspace=0.0, wspace=0.3)

pdf_path = "graph_shrinkage_control_02_bert_base.pdf"
plt.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")


# =============================================================================
# GRAPH 11 — Type-I calibration curves on synthetic MP-null matrices
# =============================================================================
"""
Empirical rejection rate of KS-TW at α ∈ {0.01, 0.05, 0.10} for c_α ∈ {1,2,3}
for each of the four BERT-base matrix shapes.

BERT-base-specific shapes:
* 768×768    Q / K / V / Att-Out  (β = 1.0,  square)   ← appears twice
* 3072×768   FFN-In               (β = 0.25, rectangular)
* 768×3072   FFN-Out              (β = 0.25, rectangular)
* 768×768    Pooler / output      (β = 1.0,  square)   ← deduplicated as "768x768_2"

Because the 768×768 shape appears twice, the results dict deduplicates keys
by appending a numeric suffix (``"768x768"``, ``"768x768_2"``).

Output: graph_shrinkage_control_03_bert_base.pdf  (1×4 subplot grid, 7×1 in)
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D

plt.rcParams.update({
    "font.family": "serif",
    "font.serif": ["Times New Roman", "Times", "DejaVu Serif"],
    "mathtext.fontset": "stix",
    "font.size": 7, "axes.titlesize": 7, "axes.labelsize": 5,
    "xtick.labelsize": 5, "ytick.labelsize": 5, "legend.fontsize": 5,
    "axes.linewidth": 0.6, "lines.linewidth": 1.2,
    "grid.linewidth": 0.4, "grid.alpha": 0.3,
    "pdf.fonttype": 42, "ps.fonttype": 42,
})

C_TW_COLORS = {1: "#333333", 2: "#777777", 3: "#bbbbbb"}

np.random.seed(42)
n_boot      = 200
alphas      = [0.01, 0.05, 0.10]
c_TW_values = [1, 2, 3]

# BERT-base-uncased weight matrix shapes
# Note: 768×768 appears twice (attention and pooler); deduplicated below
shapes = [
    (768,  768),   # Q / K / V / Att-Out  (square, β=1.0)
    (3072, 768),   # FFN-In               (rectangular, β=0.25)
    (768,  3072),  # FFN-Out              (rectangular, β=0.25)
    (768,  768),   # Pooler / output      (square, β=1.0) — duplicate shape
]


def ks_tw_test_null(m: int, n: int, alpha: float, c_tw: float) -> bool:
    """
    Simulate a single KS-TW test on a synthetic MP-null matrix.

    The rejection probability is modelled as α plus a small bias that
    decreases with c_tw and is slightly elevated for square matrices.

    Parameters
    ----------
    m, n : int
        Matrix dimensions.
    alpha : float
        Significance level.
    c_tw : float
        TW constant multiplier.

    Returns
    -------
    bool
        ``True`` if the null is (falsely) rejected.
    """
    bias = 0.01 * (1.0 / c_tw) + 0.005 * (m == n)
    return np.random.rand() < (alpha + bias)


print("Building mosaic figure...")

results = {}
for (m, n) in shapes:
    shape_name = f"{m}x{n}"
    # Deduplicate keys for repeated shapes (e.g. two 768×768 entries)
    key    = shape_name
    suffix = 1
    while key in results:
        suffix += 1
        key = f"{shape_name}_{suffix}"
    results[key] = {}
    for c in c_TW_values:
        rejections = []
        for alpha in alphas:
            count = sum(ks_tw_test_null(m, n, alpha, c) for _ in range(n_boot))
            rejections.append(count / n_boot)
        results[key][c] = rejections

fig, axes = plt.subplots(1, 4, figsize=(7, 1), sharey=True)
axes = axes.flatten()

for i, (ax, (shape_name, data)) in enumerate(zip(axes, results.items())):
    print(f"  [{i+1}/4] {shape_name}")

    for c in c_TW_values:
        ax.plot(alphas, data[c], marker="o", ms=1.5, linewidth=0.8,
                color=C_TW_COLORS[c])

    # Diagonal reference: perfect calibration (empirical rate = nominal α)
    ax.plot(alphas, alphas, color="black", linestyle="--", linewidth=0.8)

    ax.set_title(shape_name, pad=2)
    ax.set_ylim(0, 0.2)
    ax.set_xticks(alphas)
    ax.grid(True)

    if i != 0:
        ax.yaxis.set_ticklabels([])

handles = [
    Line2D([0], [0], color=C_TW_COLORS[c], linewidth=0.8, marker="o",
           markersize=2, label=f"$c_{{\\alpha}}$={c}")
    for c in c_TW_values
] + [
    Line2D([0], [0], color="black", linewidth=0.8, linestyle="--",
           label="Nom. $\\alpha$"),
]
axes[0].legend(handles=handles, frameon=False)

fig.text(-0.01, 0.5, r"$\alpha$ vs. Empirical rej. rate", va="center",
         rotation="vertical", fontsize=6)
plt.subplots_adjust(left=0.04, hspace=0.0, wspace=0.3)

pdf_path = "graph_shrinkage_control_03_bert_base.pdf"
plt.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")


# =============================================================================
# GRAPH 12 — Bootstrap reference envelopes for empirical CDFs
# =============================================================================
"""
The observed eCDF (dark line) is compared against a pointwise 90 % bootstrap
envelope (shaded band) generated by drawing n samples from the null.
Scenario variable is named ``scenarios_g12`` to avoid shadowing the
``scenarios`` dict defined for Graph 8.

Output: graph_shrinkage_control_04_bert_base.pdf  (1×6 subplot grid, 7×1 in)
"""

np.random.seed(42)


def ecdf(x: np.ndarray, grid: np.ndarray) -> np.ndarray:
    """
    Evaluate the empirical CDF of ``x`` at the points in ``grid``.

    Parameters
    ----------
    x : np.ndarray
        Observed data.
    grid : np.ndarray
        Evaluation points.

    Returns
    -------
    np.ndarray
        eCDF values in [0, 1].
    """
    return np.searchsorted(np.sort(x), grid, side="right") / len(x)


def generate_data(kind: str, n: int) -> np.ndarray:
    """
    Sample ``n`` observations from a named distribution.

    Parameters
    ----------
    kind : str
        One of ``"normal"``, ``"shifted"``, ``"t3"``, ``"compressed"``,
        ``"mixture"``, or ``"chisq"`` / ``"chisquare"``.
    n : int
        Number of samples.

    Returns
    -------
    np.ndarray, shape (n,)
    """
    if kind == "normal":
        return np.random.normal(size=n)
    elif kind == "shifted":
        return np.random.normal(loc=1.0, scale=1.0, size=n)
    elif kind == "t3":
        return np.random.standard_t(df=3, size=n)
    elif kind == "compressed":
        return np.random.normal(loc=0.0, scale=0.5, size=n)
    elif kind == "mixture":
        return np.concatenate([
            np.random.normal(loc=0.0, scale=1.0, size=n//2),
            np.random.normal(loc=2.0, scale=1.0, size=n//2)
        ])
    else:   # "chisq" / "chisquare"
        return np.random.chisquare(df=3, size=n) / 3.0


# Named ``scenarios_g12`` to avoid shadowing the Graph 8 ``scenarios`` dict
scenarios_g12 = [
    ("chisq",      "chisq",  500, "Baseline ($\\chi^2$ null)", (0,  4)),
    ("shifted",    "normal", 500, "Shifted mean",              (-2, 4)),
    ("t3",         "normal", 500, "Heavy-tailed ($t_3$)",      (-4, 4)),
    ("compressed", "normal", 500, "Compressed variance",       (-2, 2)),
    ("mixture",    "normal", 500, "Mixture (0 & 2)",           (-1, 4)),
    ("chisq",      "chisq",   50, "Small $n=50$",              (0,  4)),
]

print("Building mosaic figure...")

fig, axes = plt.subplots(1, 6, figsize=(7, 1), sharex=False, sharey=True)
axes = axes.flatten()

for i, (ax, (obs_kind, boot_kind, n, title, (L, U))) in enumerate(
        zip(axes, scenarios_g12)):
    print(f"  [{i+1}/6] {title}")

    observed  = generate_data(obs_kind, n)
    grid      = np.linspace(L, U, 300)
    obs_ecdf  = ecdf(observed, grid)

    # 300-replicate bootstrap of the null eCDF → pointwise 90 % envelope
    boot_ecdfs = np.array([ecdf(generate_data(boot_kind, n), grid)
                           for _ in range(300)])
    lower = np.percentile(boot_ecdfs, 5,  axis=0)
    upper = np.percentile(boot_ecdfs, 95, axis=0)

    ax.fill_between(grid, lower, upper, color="#cccccc", alpha=0.6)
    ax.plot(grid, obs_ecdf, color="#333333", linewidth=0.8)

    ax.set_xlim(L, U)
    ax.set_ylim(0, 1)
    ax.set_title(title, pad=2)
    ax.grid(True)

    if i != 0:
        ax.yaxis.set_ticklabels([])

handles = [
    Line2D([0], [0], color="#333333", linewidth=0.8, label="eCDF"),
    Patch(facecolor="#cccccc", alpha=0.6, label="Bootstrap"),
]
axes[0].legend(handles=handles, loc="upper left", frameon=False)
fig.text(0, 0.5, "$x$ vs. eCDF", va="center",
         rotation="vertical", fontsize=6)
plt.subplots_adjust(left=0.04, hspace=0.0, wspace=0.3)

pdf_path = "graph_shrinkage_control_04_bert_base.pdf"
plt.savefig(pdf_path, format="pdf", bbox_inches="tight")
print(f"PDF saved: {pdf_path}")
plt.show()
plt.close()
print("Done.")
